### ISSUE TITLE
Rust ?

### ISSUE THREAD

**Issue by oz** [costajob/app-servers#8]
Hi!

It would be nice to maybe include Rust in this little benchmark.

The standard lib does not ship with an HTTP server, but the folks of the [Iron framework](http://ironframework.io/) are doing a very decent job. :smile:

**Comment by costajob** [comment]
Hi,

Thanks for suggestions, i will surely gave it a try: indeed i had a raw iron server benchmarked some months ago and it was speedy!

I will add it soon!

**Comment by costajob** [comment]
Added Rust+Iron to the pack: i was expecting a better throughput anyway.
I will try to run benchmarks on a new workstation (SSD) once i will get it, to see if the numbers changes.

Best

**Comment by oz** [comment]
Cool, thanks for trying Rust! :smile: 

Iron is probably so slow because it includes a whole router. I think it compares more to Sinatra or Kemal than a bare HTTP server. Maybe it could be more optimized, but it's nice for a "hello world" bench.

I just verified that using the [hyper HTTP server lib](https://github.com/hyperium/hyper/blob/master/examples/hello.rs) that power Iron is a lot faster: wrk2 gives +/- 79k req/sec. It's still terrible but running on battery on my 2011 Lenovo X220, it's not so bad. :innocent: 

If you're curious, use Hyper's example with a Cargo.toml like this one:

```toml
[package]
name = "hyper-server"
version = "0.1.0"

[dependencies]
hyper = { git = "https://github.com/hyperium/hyper.git" }
env_logger = "*"
num_cpus = "*"
```

Cheers!
